version: 2
jobs:
  build_and_test:
    docker:
      - image: chusalvarez/spotathome
    working_directory: ~/spotathome
    steps:
      - checkout
      - run:
          name: Run tests
          command: export LD_LIBRARYPATH=/usr/local/lib && make test
      - run:
          name: build main binary
          command: export LD_LIBRARYPATH=/usr/local/lib && make buildmain
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build_and_test
